### ISSUE TITLE
I think it would be a good idea to have the bot give a warning when its going to go offline for maintenance/updates.

### ISSUE THREAD

**Issue by Blatantist** [HexCodeFFF/mediaforge#64]
My friends in the server have been getting annoyed by the bot going offline pretty often. I assume you're just updating it, but a warning would be nice, and if possible, say for how long it will be down.

**Comment by HexCodeFFF** [comment]
Maitinence generally only involves a couple minutes of downtime to upload new code to the bot snd restart it. Unfortunately most of the downtime is just server issues because I don’t have the money for proper hosting so it runs off a pc in my basement. I have a statuscake thing set up with a link to it somewhere in the mediaforge discord to let me know when it goes down but it doesn’t account for the bot being overloaded and freezing

**Comment by Blatantist** [comment]
Understood. I may just host it myself then

**Comment by Blatantist** [comment]
Well good luck eventually being able to host it lol.
